# Generated by Django 3.1.2 on 2020-12-02 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20201201_1910'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('streetOne', models.CharField(max_length=100)),
                ('streetTwo', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=16)),
                ('zipcode', models.CharField(max_length=5)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
